### Themes
#
include ~/.config/sway/themes/catppuccin.conf


### Wallpaper
#
# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
# output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
# output * bg ~/Pictures/Archlinux/wallpaper/split.png fill
#
exec_always ~/.local/bin/swaybg-set-wallpaper


# font pango:Noto Sans CJK SC 9.5
font pango:monospace 10

# Cursor theme and size
seat seat0 xcursor_theme volantes_cursors 32

# Hiding title bar for only single window in the workspace
default_border pixel 2

gaps inner 5px
# gaps outer 1px
