### Input configuration
#
# Read `man 5 sway-input` for more information about this section.
#
input type:touchpad {
    # Enable tapping
    tap enabled

    # Enable Disable-While-Typing
    dwt enabled

    # Use two-finger scrolling
    scroll_method "two_finger"

    # Disable touchpad when an external mouse is connected
    dwtp disabled_on_external_mouse
}

input type:keyboard {
    # xkb_layout "eu"
    xkb_options "caps:escape_shifted_capslock"
    xkb_numlock enable
}

