### Output configuration
#
# Example configuration:
#
#   output HDMI-A-1 resolution 1920x1080 position 1920,0
#
# You can get the names of your outputs by running: swaymsg -t get_outputs
#
set $monitor_laptop eDP-1
set $monitor_external DP-3


output $monitor_external {
    mode 1920x1080@260Hz
    pos 0 0
    adaptive_sync on
}
output $monitor_laptop {
    mode 2560x1600@165Hz
    scale 2
    pos 1920 0
    adaptive_sync on
}


workspace 1 output $monitor_external
workspace 2 output $monitor_external
workspace 3 output $monitor_external
workspace 4 output $monitor_external
workspace 5 output $monitor_external

workspace 6 output $monitor_laptop
workspace 7 output $monitor_laptop
workspace 8 output $monitor_laptop
workspace 9 output $monitor_laptop
workspace 10 output $monitor_laptop
