## Set specific windows to floating mode
set $floating_size_x 2550 set $floating_size_y 1550

## upper left corner: (x,y)
set $floating_position_x 5
set $floating_position_y 45



for_window [shell="xwayland"] title_format "[XWayland] %title"

## Custom app_id type
for_window [app_id="Float"] floating enable, resize set 2000 1400, move absolute position center

for_window [window_role="app"]                      floating enable
for_window [window_role="pop-up"]                   floating enable
for_window [window_role="task_dialog"]              floating enable
for_window [title="Preferences$"]                   floating enable
for_window [title="Picture-in-Picture"]             floating enable sticky enable
for_window [title="图片查看器"]                     floating enable sticky enable


## Waylyrics
for_window [app_id="waylyrics"] floating enable, border none, sticky enable, resize set 1600 200, move window to position 60 850
no_focus [app_id="waylyrics"]


## Assign settings - Special worksapce for applications
assign [app_id="firefox"] $ws2
assign [app_id="spotify"] $ws3
assign [title="Steam"] $ws4
assign [app_id="hmcl"] $ws5
assign [app_id="dolphin"] $ws6
assign [app_id="thunar"] $ws6
assign [app_id="obsidian"] $ws7
assign [app_id="TelegramDesktop"] $ws8
assign [app_id="discord"] $ws8
assign [app_id="wechat"] $ws9
assign [app_id="^QQ$"] $ws9
# assign [app_id="qBittorrent"] $ws10


## Move to scratchpad
for_window [app_id="keepassxc" title=".kdbx"] move to scratchpad
for_window [title="Mozilla Thunderbird"] move scratchpad
for_window [app_id="qBittorrent" title="qBittorrent Enhanced Edition"] move to scratchpad


## Move position to center
# for_window [app_id="Navigator" app_id="librewolf"] move absolute position center
