# [Themes]
include ~/.config/i3/themes/catppuccin.conf
# include ~/.config/i3/themes/monokai.conf
# include ~/.config/i3/themes/kanagawa-wave.conf


# [Wallpaper]
exec_always ~/.local/bin/wallpaper


# [Window Settings]
#
font pango:monospace 10

# Hiding title bar for only single window in the workspace
set $border 2

default_border pixel $border
for_window [class=".*"] border pixel $border
default_floating_border pixel $border

# smart_borders on

gaps inner 8px
# gaps outer 3px

# Display all floating windows regardless to which application they belong to
popup_during_fullscreen all

# Enable window icons for all windows
for_window [all] title_window_icon on
