# vim:foldmethod=marker
### Output configuration
#
set $monitor_laptop eDP-1
set $monitor_external DP-1

# xrandr
#
# [External monitor only] {{{
#
# exec --no-startup-id xrandr \
#     --output $monitor_external \
#         --primary \
#         --mode 1920x1080 \
#         --rate 260.00 \
#         --pos 0x0 \
#         --rotate normal \
#     --output $monitor_laptop --off

    # With laptop monitor
    #
    # --output $monitor_laptop \
    #     --primary \
    #     --mode 2560x1600 \
    #     --rate 165.00 \
    #     --pos 1920x0
# }}}
#
# [Laptop monitor only] {{{
#
# exec --no-startup-id xrdb -load <<< 'Xft.dpi: 144'
exec --no-startup-id xrdb -load ~/.Xresources

exec --no-startup-id xrandr \
    --output $monitor_laptop \
    --mode 2560x1600 \
    --rate 165.00
# }}}


# workspace 1 output $monitor_external
# workspace 2 output $monitor_external
# workspace 3 output $monitor_external
# workspace 4 output $monitor_external
# workspace 5 output $monitor_external
#
# workspace 6 output $monitor_laptop
# workspace 7 output $monitor_laptop
# workspace 8 output $monitor_laptop
# workspace 9 output $monitor_laptop
# workspace 10 output $monitor_laptop
