### Applications
#

# exec pot
# exec --no-startup-id greenclip daemon
# exec_always --no-startup-id thunar --daemon

## i3-msg 'exec --no-startup-id <xxx>' - use with scratchpad
# exec --no-startup-id i3-msg 'exec thunderbird'
# exec --no-startup-id i3-msg 'exec keepassxc'
# exec --no-startup-id i3-msg 'exec qbittorrent'



### Scripts and commands
#
# Xwayland HiDPI
# xwayland disabled
# exec_always --no-startup-id [ ! pgrep -f xwayland-satellite ] || \
#     xwayland-satellite :0 && \
#     DISPLAY=:0 xrdb -load <<< 'Xft.dpi: 144'

# exec ~/.config/wob/wobpipe
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec --no-startup-id udiskie
exec --no-startup-id dunst
# exec --no-startup-id timeshift
exec --no-startup-id keepassxc
exec --no-startup-id thunderbird
# exec --no-startup-id flclash
# exec --no-startup-id qbittorrent
exec --no-startup-id numlockx
exec --no-startup-id ~/.config/xob/xobpipe

exec_always --no-startup-id fcitx5 -d
exec_always --no-startup-id picom

### Idle configuration
#
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock-fancy
# exec --no-startup-id xset s 300
# exec --no-startup-id xset dpms 310 310 310
