# vim:foldmethod=marker

# [Scripts & commands] {{
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec_always --no-startup-id "pkill picom; picom"
exec --no-startup-id ~/.config/xob/xobpipe
exec_always --no-startup-id "pkill dunst; dunst"
# exec --no-startup-id redshift
exec --no-startup-id udiskie
exec --no-startup-id xrdb -merge ~/.Xresources
# }}}


# [Software] {{
exec_always --no-startup-id fcitx5 -d
exec --no-startup-id keepassxc
exec --no-startup-id thunderbird
# exec --no-startup-id emacs --daemon
# exec --no-startup-id flclash
# exec --no-startup-id qbittorrent
# }}}


# [Idle] {{
# exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock-fancy -n
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock -n -e -i ~/Pictures/Wallpapers/i3lock/1.png
exec --no-startup-id xset s 1800
exec --no-startup-id xset dpms 1810 1810 1810
# }}}
