### Applications
#

# exec pot
# exec --no-startup-id greenclip daemon
# exec_always --no-startup-id thunar --daemon

## i3-msg 'exec --no-startup-id <xxx>' - use with scratchpad
# exec --no-startup-id i3-msg 'exec thunderbird'
# exec --no-startup-id i3-msg 'exec keepassxc'
# exec --no-startup-id i3-msg 'exec qbittorrent'



### Scripts and commands
#
# Xwayland HiDPI
# xwayland disabled
# exec_always --no-startup-id [ ! pgrep -f xwayland-satellite ] || \
#     xwayland-satellite :0 && \
#     DISPLAY=:0 xrdb -load <<< 'Xft.dpi: 144'

# exec ~/.config/wob/wobpipe
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec_always foot --server

exec udiskie
# exec gammastep
exec keepassxc
exec thunderbird
exec_always fcitx5 -d
# exec clash-verge
# exec flclash
# exec qbittorrent


### Idle configuration
#
# Example configuration:
#
# exec swayidle -w \
#          timeout 300 'swaylock -f -c 000000' \
#          timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
#          before-sleep 'swaylock -f -c 000000'
#
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.

# exec swayidle -w \
#     timeout 300 '~/.local/bin/swaylock-fancy' \
#     timeout 310 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
#     before-sleep '~/.local/bin/swaylock-fancy'
