# Kanagawa color theme for Zathura
# To switch between backgrounds, use <C-r>

#
# Kanagawa color theme
#
set notification-error-bg       rgba(195,64,67,1)     # Autumn Red
set notification-error-fg       rgba(220,215,186,1)   # Fuji White
set notification-warning-bg     rgba(255,158,100,1)   # Boat Yellow
set notification-warning-fg     rgba(22,22,29,1)      # Sumi Ink 0
set notification-bg             rgba(22,22,29,1)      # Sumi Ink 0
set notification-fg             rgba(220,215,186,1)   # Fuji White

set completion-bg               rgba(31,31,40,1)      # Sumi Ink 1
set completion-fg               rgba(114,113,105,1)   # Fuji Gray
set completion-group-bg         rgba(31,31,40,1)      # Sumi Ink 1
set completion-group-fg         rgba(114,113,105,1)   # Fuji Gray
set completion-highlight-bg     rgba(42,42,55,1)      # Sumi Ink 2
set completion-highlight-fg     rgba(220,215,186,1)   # Fuji White

set index-bg                    rgba(31,31,40,1)      # Sumi Ink 1
set index-fg                    rgba(220,215,186,1)   # Fuji White
set index-active-bg             rgba(42,42,55,1)      # Sumi Ink 2
set index-active-fg             rgba(149,127,184,1)   # Oni Violet

set inputbar-bg                 rgba(22,22,29,1)      # Sumi Ink 0
set inputbar-fg                 rgba(220,215,186,1)   # Fuji White
set statusbar-bg                rgba(22,22,29,1)      # Sumi Ink 0
set statusbar-fg                rgba(220,215,186,1)   # Fuji White

set highlight-color             rgba(126,156,216,0.5) # Crystal Blue
set highlight-active-color      rgba(149,127,184,0.5) # Oni Violet

set default-bg                  rgba(31,31,40,1)      # Sumi Ink 1
set default-fg                  rgba(220,215,186,1)   # Fuji White

set render-loading              true
set render-loading-fg           rgba(31,31,40,1)      # Sumi Ink 1
set render-loading-bg           rgba(220,215,186,1)   # Fuji White

#
# Recolor mode settings
#

set recolor                     true
set recolor-lightcolor          rgba(31,31,40,1)      # Sumi Ink 1
set recolor-darkcolor           rgba(220,215,186,1)   # Fuji White

#
# Loading animation
#
set render-loading true
set render-loading-fg "#dcd7ba"
set render-loading-bg "#1f1f28"
