[manager]
linemode = "size"

[preview]
max_width = 1000
max_height = 800

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
