[manager]
linemode = "size"

[preview]
max_width = 1000
max_height = 800

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
view = [
  { run = 'feh "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

# [open]
# prepend_rules = [
#   { name = "*.jpg", use = "view" },
#   { name = "*.png", use = "view" },
#   # { name = "*.gif", use = "view" },
#   { name = "*.webp", use = "view" },
#   { name = "*.avif", use = "view" },
#   { name = "*.svg", use = "view" },
# ]

