# Seek
#
h seek -5
Ctrl+h seek -60
H frame-back-step
Shift+LEFT frame-back-step

l seek 5
Ctrl+l seek 60
L frame-step
Shift+RIGHT frame-step


# Volume
#
AXIS_UP add volume 2
UP add volume 2
+ add volume 2
Shift+UP add volume 10

AXIS_DOWN add volume -2
DOWN add volume -2
- add volume -2
Shift+DOWN add volume -10


# Subtitle and Audio
#
x add sub-delay +0.042
c add sub-delay -0.042
b add audio-delay +0.042
n add audio-delay -0.042


# Other
#
y cycle deband
a ab-loop
A cycle-values sub-ass-override "no" "strip"
