# Volume
#
AXIS_UP add volume 2
UP add volume 2
+ add volume 2
Shift+UP add volume 10

AXIS_DOWN add volume -2
DOWN add volume -2
- add volume -2
Shift+DOWN add volume -10


# Frame Step
#
Shift+RIGHT frame-step
Shift+LEFT frame-back-step


# Subtitle and Audio
#
x add sub-delay +0.042
c add sub-delay -0.042
b add audio-delay +0.042
n add audio-delay -0.042
