#!/usr/bin/env bash
# @author Allen
# @since 2025.11

get_battery_icon() {
    bat_int=$1
    if [ "$bat_int" -le 5 ]; then
        echo "󰂎"
    elif [ "$bat_int" -le 10 ]; then
        echo "󰁺"
    elif [ "$bat_int" -le 20 ]; then
        echo "󰁻"
    elif [ "$bat_int" -le 30 ]; then
        echo "󰁼"
    elif [ "$bat_int" -le 40 ]; then
        echo "󰁽"
    elif [ "$bat_int" -le 50 ]; then
        echo "󰁾"
    elif [ "$bat_int" -le 60 ]; then
        echo "󰁿"
    elif [ "$bat_int" -le 70 ]; then
        echo "󰂀"
    elif [ "$bat_int" -le 80 ]; then
        echo "󰂁"
    elif [ "$bat_int" -le 90 ]; then
        echo "󰂂"
    else
        echo "󰁹"
    fi
}

get_battery_charging_icon() {
    bat_int=$1
    if [ "$bat_int" -le 5 ]; then
        echo "󰢟"
    elif [ "$bat_int" -le 10 ]; then
        echo "󰢜"
    elif [ "$bat_int" -le 20 ]; then
        echo "󰂆"
    elif [ "$bat_int" -le 30 ]; then
        echo "󰂇"
    elif [ "$bat_int" -le 40 ]; then
        echo "󰂈"
    elif [ "$bat_int" -le 50 ]; then
        echo "󰢝"
    elif [ "$bat_int" -le 60 ]; then
        echo "󰂉"
    elif [ "$bat_int" -le 70 ]; then
        echo "󰢞"
    elif [ "$bat_int" -le 80 ]; then
        echo "󰂊"
    elif [ "$bat_int" -le 90 ]; then
        echo "󰂋"
    else
        echo "󰂅"
    fi
}

battery_status=$(acpi -b)
battery_level=$(echo "$battery_status" | grep -oE '[0-9]{1,3}?%' | tr -d '%')

if echo "$battery_status" | grep -q "Discharging"; then
    battery_icon="$(get_battery_icon "$battery_level")"
    remaining_time=$(echo "$battery_status" | grep -oE '[0-9]{2}:[0-9]{2}')
    echo "[$battery_icon $battery_level% $remaining_time]"
else
    battery_icon="$(get_battery_charging_icon "$battery_level")"
    echo "[$battery_icon $battery_level%]"
fi

# [ "$battery_level" -le 20 ] && exit 33
exit 0
