#!/bin/bash
# @author Allen
# @since 2025.11

get_battery_icon() {
    bat_int=$1
    if [ "$bat_int" -le 5 ]; then
        echo "󰂎"
    elif [ "$bat_int" -le 10 ]; then
        echo "󰁺"
    elif [ "$bat_int" -le 20 ]; then
        echo "󰁻"
    elif [ "$bat_int" -le 30 ]; then
        echo "󰁼"
    elif [ "$bat_int" -le 40 ]; then
        echo "󰁽"
    elif [ "$bat_int" -le 50 ]; then
        echo "󰁾"
    elif [ "$bat_int" -le 60 ]; then
        echo "󰁿"
    elif [ "$bat_int" -le 70 ]; then
        echo "󰂀"
    elif [ "$bat_int" -le 80 ]; then
        echo "󰂁"
    elif [ "$bat_int" -le 90 ]; then
        echo "󰂂"
    else
        echo "󰁹"
    fi
}

get_battery_charging_icon() {
    bat_int=$1
    if [ "$bat_int" -le 5 ]; then
        echo "󰢟"
    elif [ "$bat_int" -le 10 ]; then
        echo "󰢜"
    elif [ "$bat_int" -le 20 ]; then
        echo "󰂆"
    elif [ "$bat_int" -le 30 ]; then
        echo "󰂇"
    elif [ "$bat_int" -le 40 ]; then
        echo "󰂈"
    elif [ "$bat_int" -le 50 ]; then
        echo "󰢝"
    elif [ "$bat_int" -le 60 ]; then
        echo "󰂉"
    elif [ "$bat_int" -le 70 ]; then
        echo "󰢞"
    elif [ "$bat_int" -le 80 ]; then
        echo "󰂊"
    elif [ "$bat_int" -le 90 ]; then
        echo "󰂋"
    else
        echo "󰂅"
    fi
}

DISCHARGING=$(acpi -b | grep -q "Discharging")
echo "$DISCHARGING"

BAT=$(acpi -b | grep -E -o '[0-9]{1,3}?%' | tr -d '%')

# if; then
#     BAT_ICON="$(get_battery_icon "$BAT")"
# else
#     BAT_ICON="$(get_battery_charging_icon "$BAT")"
# fi

# echo "$BAT_ICON $BAT%"

# Set urgent flag below 5% or use orange below 20%
# [ "${BAT%?}" -le 5 ] && exit 33
# [ "${BAT%?}" -le 20 ] && echo "#FF8000"
