#!/bin/bash
# @author Allen
# @since 2025
# Generates brightness status for i3blocks.
# WARN: Dependencies: brightnessctl

get_light_icon() {
    BRIGHTNESS_INT=$1
    if [ "$BRIGHTNESS_INT" -le 10 ]; then
        echo "󰃞"
    elif [ "$BRIGHTNESS_INT" -le 40 ]; then
        echo "󰃝"
    elif [ "$BRIGHTNESS_INT" -le 70 ]; then
        echo "󰃟"
    else
        echo "󰃠"
    fi
}

BRIGHTNESS_PERCENT=$(brightnessctl -m | awk -F, '{print $4}' | tr -d '%')
BRIGHTNESS_ICON=$(get_light_icon "$BRIGHTNESS_PERCENT")

echo "$BRIGHTNESS_ICON $BRIGHTNESS_PERCENT%"
