#!/usr/bin/env bash
# @author Allen
# @since 2025
# Generates brightness status for i3blocks and controls it with the mouse wheel.
# WARN: Dependencies: brightnessctl, wob

WOB_PIPE=/tmp/wobpipe
STEP=5
# BACKLIGHT_CLASS=backlight

# Catching i3blocks click
if [ -n "$BLOCK_BUTTON" ]; then
    case $BLOCK_BUTTON in
    4)
        brightnessctl set +$STEP% >/dev/null 2>&1
        ;;
    5)
        brightnessctl set $STEP%- >/dev/null 2>&1
        ;;
    esac
fi

get_light_icon() {
    brightness_int=$1
    if [ "$brightness_int" -le 10 ]; then
        echo "󰃞"
    elif [ "$brightness_int" -le 40 ]; then
        echo "󰃝"
    elif [ "$brightness_int" -le 70 ]; then
        echo "󰃟"
    else
        echo "󰃠"
    fi
}

brightness_percent=$(brightnessctl -m | awk -F, '{print $4}' | tr -d '%')
brightness_icon=$(get_light_icon "$brightness_percent")

# wob
if [ -n "$BLOCK_BUTTON" ]; then
    echo "[${brightness_percent%\%}" >"$WOB_PIPE]"
fi

echo "[$brightness_icon $brightness_percent%]"

pkill -SIGRTMIN+3 i3blocks

exit 0
