#!/bin/bash

# Get current hour (1-12) for the icon
HOUR=$(date +%I | sed 's/^0//')

# Assign Nerd Font clock icon based on the hour
case $HOUR in
1) ICON="󱐿" ;;
2) ICON="󱑀" ;;
3) ICON="󱑁" ;;
4) ICON="󱑂" ;;
5) ICON="󱑃" ;;
6) ICON="󱑄" ;;
7) ICON="󱑅" ;;
8) ICON="󱑆" ;;
9) ICON="󱑇" ;;
10) ICON="󱑈" ;;
11) ICON="󱑉" ;;
12) ICON="󱑊" ;;
*) ICON="" ;; # Fallback
esac

# Output for i3blocks
echo "[$ICON $(LC_TIME=C date '+%Y-%m-%d %a %H:%M')] "
