#!/usr/bin/env bash
# @author Allen
# @since 2025
# Generates microphone status for i3blocks.
# WARN: Dependencies: wpctl, bc

WOB_PIPE=/tmp/wobpipe
SOURCE=@DEFAULT_AUDIO_SOURCE@
source_status=$(wpctl get-volume "$SOURCE")
STEP=0.01

# Catching i3blocks click
if [ -n "$BLOCK_BUTTON" ]; then
    case $BLOCK_BUTTON in
    1) LANGUAGE=zh_CN pavucontrol ;;
    3) LANGUAGE=zh_CN pavucontrol ;;
    4) wpctl set-volume "$SOURCE" "$STEP"+ >/dev/null 2>&1 ;;
    5) wpctl set-volume "$SOURCE" "$STEP"- >/dev/null 2>&1 ;;
    esac
fi

if echo "$source_status" | grep -q 'MUTED'; then
    source_volume="MUTE"
    source_icon=" "
else
    source_volume_factor=$(echo "$source_status" | grep -oE '[0-9]+\.[0-9]+')
    source_volume=$(echo "$source_volume_factor * 100" | bc | awk '{print int($1)}')
    source_icon=""
fi

# wob
if [ "$BLOCK_BUTTON" == 3 ] || [ "$BLOCK_BUTTON" == 4 ]; then
    if [ "$source_volume" == "MUTE" ]; then
        echo "0" >"$WOB_PIPE"
    else
        echo "$source_volume" >"$WOB_PIPE"
    fi
fi

if [ "$source_volume" == "MUTE" ]; then
    echo "[$source_icon]"
    echo
    echo "#777777"
else
    echo "[$source_icon$source_volume%]"
fi

pkill -SIGRTMIN+2 i3blocks

exit 0
