#!/bin/bash
# @author Allen
# @since 2025
# Generates speaker status for i3blocks.
# WARN: Dependencies: wpctl, bc
get_sink_icon() {
    VOLUME=$1
    if [ "$VOLUME" -le 33 ]; then
        echo ""
    elif [ "$VOLUME" -le 66 ]; then
        echo ""
    else
        echo ""
    fi
}

SINK_STATUS=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

if echo "$SINK_STATUS" | grep -q 'MUTED'; then
    SINK_VOLUME="MUTE"
    SINK_ICON="󰝟"
else
    SINK_VOLUME_FACTOR=$(echo "$SINK_STATUS" | grep -oE '[0-9]+\.[0-9]+')
    SINK_VOLUME_INT=$(echo "$SINK_VOLUME_FACTOR * 100" | bc | awk '{print int($1)}')
    SINK_VOLUME="$SINK_VOLUME_INT"
    SINK_ICON=$(get_sink_icon "$SINK_VOLUME_INT")
fi

SINK_DISPLAY="${SINK_VOLUME}%"

if [ "$SINK_VOLUME" == "MUTE" ]; then
    # SINK_DISPLAY="MUTE"
    SINK_DISPLAY=""
fi

echo "$SINK_ICON $SINK_DISPLAY"
