#!/bin/bash
# @author Allen
# @since 2025
# Generates speaker status for i3blocks.
# WARN: Dependencies: wpctl, bc

WOB_PIPE=/tmp/wobpipe
SINK=@DEFAULT_SINK@
SINK_STATUS=$(wpctl get-volume "$SINK")

# Catching i3blocks click
if [ -n "$BLOCK_BUTTON" ]; then
    case $BLOCK_BUTTON in
    1) pavucontrol ;;
    2) pavucontrol ;;
    4) wpctl set-volume "$SINK" 0.01+ >/dev/null 2>&1 ;;
    5) wpctl set-volume "$SINK" 0.01- >/dev/null 2>&1 ;;
    esac
fi

get_sink_icon() {
    VOLUME=$1
    if [ "$VOLUME" -le 33 ]; then
        echo ""
    elif [ "$VOLUME" -le 66 ]; then
        echo ""
    else
        echo ""
    fi
}

if echo "$SINK_STATUS" | grep -q 'MUTED'; then
    SINK_VOLUME="MUTE"
    SINK_ICON="󰝟"
else
    SINK_VOLUME_FACTOR=$(echo "$SINK_STATUS" | grep -oE '[0-9]+\.[0-9]+')
    SINK_VOLUME_INT=$(echo "$SINK_VOLUME_FACTOR * 100" | bc | awk '{print int($1)}')
    SINK_VOLUME="$SINK_VOLUME_INT"
    SINK_ICON=$(get_sink_icon "$SINK_VOLUME_INT")
fi

# wob
# if [ -n "$BLOCK_BUTTON" ]; then
if [ "$BLOCK_BUTTON" == 3 ] || [ "$BLOCK_BUTTON" == 4 ]; then
    if [ "$SINK_VOLUME" == "MUTE" ]; then
        echo "0" >"$WOB_PIPE"
    else
        echo "$SINK_VOLUME" >"$WOB_PIPE"
    fi
fi

SINK_DISPLAY="${SINK_VOLUME}%"
if [ "$SINK_VOLUME" == "MUTE" ]; then
    # SINK_DISPLAY="MUTE"
    SINK_DISPLAY=""
fi

echo "$SINK_ICON $SINK_DISPLAY"
