#!/bin/bash
# @author Allen
# @since 2025
# Generates speaker status for i3blocks.
# WARN: Dependencies: wpctl, bc

WOB_PIPE=/tmp/wobpipe
SINK=@DEFAULT_SINK@
sink_status=$(wpctl get-volume "$SINK")
STEP=0.01

# Catching i3blocks click
if [ -n "$BLOCK_BUTTON" ]; then
    case $BLOCK_BUTTON in
    1) LANGUAGE=zh_CN pavucontrol ;;
    3) LANGUAGE=zh_CN pavucontrol ;;
    4) wpctl set-volume "$SINK" "$STEP"+ >/dev/null 2>&1 ;;
    5) wpctl set-volume "$SINK" "$STEP"- >/dev/null 2>&1 ;;
    esac
fi

get_sink_icon() {
    volume=$1
    if [ "$volume" -le 33 ]; then
        echo ""
    elif [ "$volume" -le 66 ]; then
        echo ""
    else
        echo ""
    fi
}

if echo "$sink_status" | grep -q 'MUTED'; then
    sink_volume="MUTE"
    sink_icon="󰝟"
else
    sink_volume_factor=$(echo "$sink_status" | grep -oE '[0-9]+\.[0-9]+')
    sink_volume=$(echo "$sink_volume_factor * 100" | bc | awk '{print int($1)}')
    sink_icon=$(get_sink_icon "$sink_volume")
fi

# wob
# if [ -n "$BLOCK_BUTTON" ]; then
if [ "$BLOCK_BUTTON" == 3 ] || [ "$BLOCK_BUTTON" == 4 ]; then
    if [ "$sink_volume" == "MUTE" ]; then
        echo "0" >"$WOB_PIPE"
    else
        echo "$sink_volume" >"$WOB_PIPE"
    fi
fi

if [ "$sink_volume" == "MUTE" ]; then
    echo "$sink_icon "
else
    echo "$sink_icon $sink_volume%"
fi

exit 0
