#!/usr/bin/env bash
# @author Allen
# @since 2025
#
# 'Curl' weather report from wttr.in
# https://github.com/chubin/wttr.in
# Usage: $0 [--force]

# Import $city from dotfiles/private/wttr-city
. "$HOME/private/wttr-city"

CACHE_FILE="$HOME/.cache/i3blocks-scripts/wttr-weather"
CACHE_TTL=1800   # 30min
CURL_TIMESOUT=30 # s

# One-line Output Format
# https://github.com/chubin/wttr.in?tab=readme-ov-file#one-line-output
#
# FORMAT_STRING="1"
# FORMAT_STRING="%c%t(%f)+%m\n"
FORMAT_STRING="%c%t(%f)+💧%h+🌬️%w+%m\n"
#
#     c    Weather condition,
#     C    Weather condition textual name,
#     x    Weather condition, plain-text symbol,
#     h    Humidity,
#     t    Temperature (Actual),
#     f    Temperature (Feels Like),
#     w    Wind,
#     l    Location,
#     m    Moon phase 🌑🌒🌓🌔🌕🌖🌗🌘,
#     M    Moon day,
#     p    Precipitation (mm/3 hours),
#     P    Pressure (hPa),
#     u    UV index (1-12),
#
#     D    Dawn*,
#     S    Sunrise*,
#     z    Zenith*,
#     s    Sunset*,
#     d    Dusk*,
#     T    Current time*,
#     Z    Local timezone.
#
# (*times are shown in the local timezone)

mkdir -p "$(dirname "$CACHE_FILE")"

# Updating weather by clicking button or using '--force'
# Auto updating every $TIMEOUT seconds
if [[ ! -n "$BLOCK_BUTTON" &&
    "$1" != "--force" &&
    -f "$CACHE_FILE" &&
    $(($(date +%s) - $(stat -c %Y "$CACHE_FILE"))) -lt $CACHE_TTL ]]; then

    cat "$CACHE_FILE"
    exit 0
fi

weather_raw=$(curl -s --max-time "$CURL_TIMESOUT" "wttr.in/$city?format=$FORMAT_STRING" |
    # Remove spaces after the weather emoji
    # then Convert '+12°C(+15°C)' to '12(15)°C', or '2°C(-1°C)' to '2(-1)°C'
    awk '{
        sub(/ +/,"");
        gsub(/\+/,"");
        sub(/°C\(/,"(");
        sub(/°C\)/,")°C")
    }1')

if [ -n "$weather_raw" ]; then
    echo "$weather_raw" >"$CACHE_FILE"
    echo "$weather_raw"
else
    echo " "
fi

exit 0
