#!/bin/env bash
# @author Allen
# @since 2025
# 'Curl' weather report from wttr.in
# Usage: $0 [--force]

# Import $city from dotfiles/private/wttr-city
. "$HOME/private/wttr-city"

CACHE_FILE="$HOME/.cache/i3blocks-scripts/wttr-weather"
CACHE_TTL=1800 # 30min
TIMEOUT=30     # s

mkdir -p "$(dirname "$CACHE_FILE")"

# Updating weather by clicking button or using '--force'
# Auto updating every $TIMEOUT seconds
if [[ ! -n "$BLOCK_BUTTON" &&
    "$1" != "--force" && -f "$CACHE_FILE" &&
    $(($(date +%s) - $(stat -c %Y "$CACHE_FILE"))) -lt $CACHE_TTL ]]; then
    cat "$CACHE_FILE"
    exit 0
fi

weather_raw=$(curl -s --max-time "$TIMEOUT" "wttr.in/$city?format=1" | sed 's/ //g')
if [ -n "$weather_raw" ]; then
    echo "$weather_raw" >"$CACHE_FILE"
    echo "$weather_raw"
else
    echo " "
fi

exit 0
