#!/bin/bash

# Dependencies: nmcli

# Wired interface name (e.g., eth0, enpXsX)
WIRED_IFACE="enp52s0"
wired_status="$(ip a show dev "$WIRED_IFACE")"

if echo "$wired_status" | grep -q "state UP" && echo "$wired_status" | grep -q "inet "; then
    ip=$(echo "$wired_status" | grep -oP 'inet \K[\d.]+' | head -n 1)
    echo "󰲝  $ip"
    echo "󰲝 "
else
    echo "󰲛 "
fi

[[ "$BLOCK_BUTTON" == 1 || "$BLOCK_BUTTON" == 3 ]] && LANGUAGE=zh_CN nm-connection-editor

exit 0
