#!/bin/bash

# Dependencies: nmcli

# Wired interface name (e.g., eth0, enpXsX)
WIRED_IFACE="enp52s0"
WIRED_STATUS="$(ip a show dev "$WIRED_IFACE")"

if echo "$WIRED_STATUS" | grep -q "state UP" && echo "$WIRED_STATUS" | grep -q "inet "; then
    IP=$(echo "$WIRED_STATUS" | grep -oP 'inet \K[\d.]+' | head -n 1)
    echo "󰲝  $IP"
    echo "󰲝 "
else
    echo "󰲛 "
fi

# [[ "$BLOCK_BUTTON" == 1 || "$BLOCK_BUTTON" == 3 ]] && footclient -e nmtui

exit 0
