# The status generator command.
# Optional: with no status generator the bar will display only tags and layout name.
command = "env LANGUAGE=en_US i3blocks"
# command = "i3status-rs"

# Colors: Catppuccin Macchiato/Mocha Style
background = "#11111be6"
color = "#cdd6f4ff"
separator = "#bac2deff"
tag_fg = "#cdd6f4ff"
tag_bg = "#11111bff"
tag_focused_fg = "#11111bff"
tag_focused_bg = "#cba6f7ff"
tag_urgent_fg = "#cdd6f4ff"
tag_urgent_bg = "#f38ba8ff"
tag_inactive_fg = "#45475aff"
tag_inactive_bg = "#11111bff"


# The font and various sizes
font = "Iosevka Nerd Font 10"
height = 25
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
separator_width = 2.0
tags_r = 0.0
tags_padding = 5.0
tags_margin = 0.0
blocks_r = 0.0
blocks_overlap = 0.0

# # Misc
# position = "top"                 # either "top" or "bottom"
# layer = "top"                    # one of "top", "overlay", "bottom" or "background"
# hide_inactive_tags = true
# invert_touchpad_scrolling = true
# show_tags = true
# show_layout_name = true
# blend = true                     # whether tags/blocks colors should blend with bar's background
# show_mode = true
# start_hidden = false             # whether the bar is initially in the 'hidden' state
#
# # WM-specific options
# [wm.river]
# max_tag = 9 # Show only the first nine tags
#
# # Per output overrides
# # [output.your-output-name]
# # right now only "enable" option is available
# # enable = false
# #
# # You can have any number of overrides
# # [output.eDP-1]
# # enable = false
