# Kanagawa Color
set $fujiWhite #dcd7ba
set $oldWhite  #c8c093
set $sumiInk0  #16161d
set $sumiInk1  #1f1f28
set $sumiInk2  #2a2a37
set $sumiInk3  #363646
set $oniViolet #957fb8
set $waveBlue  #7e9cd8
set $crystalBlue #7fb4ca
set $springGreen #98bb6c
set $boatYellow #c0a36e
set $autumnRed #c34043
set $waveAqua #7aa89f
set $dragonBlue #2d4f67
set $fujiGray #727169

# No indicator
# target                  title       bg          text        indicator   border
client.focused            $oniViolet  $sumiInk1   $fujiWhite  $waveAqua   $waveAqua
client.focused_inactive   $sumiInk3   $sumiInk1   $oldWhite   $sumiInk3   $sumiInk3
client.unfocused          $sumiInk3   $sumiInk1   $oldWhite   $sumiInk3   $sumiInk3
client.urgent             $autumnRed  $sumiInk1   $autumnRed  $sumiInk3   $autumnRed
client.placeholder        $sumiInk3   $sumiInk1   $fujiWhite  $sumiInk3   $sumiInk3
client.background         $sumiInk1

# bar
bar {
    # bar font
    font pango:Iosevka Nerd Font 12
    status_command LANGUAGE=en_US i3blocks
    position top

    colors {
        background         $sumiInk0
        statusline         $fujiWhite
        focused_statusline $fujiWhite
        focused_separator  $fujiWhite

        # target            border      bg          text
        focused_workspace   $sumiInk0   $waveAqua   $sumiInk0
        active_workspace    $sumiInk0   $sumiInk3   $fujiWhite
        inactive_workspace  $sumiInk0   $sumiInk0   $oldWhite
        urgent_workspace    $sumiInk0   $autumnRed  $sumiInk0
    }
}
