# Monet Palette Variables
set $base      #2c3235
set $mantle    #181d26
set $crust     #11151c
set $surface0  #363d41
set $surface1  #41494e
set $surface2  #4c555a

set $text      #d9d4d6
set $subtext1  #c6c9ba
set $subtext0  #b8b69d
set $overlay2  #8e938f
set $overlay1  #727169
set $overlay0  #5d5b5b

set $sunrise   #d7725d
set $solar     #d95043
set $meadow    #667302
set $foliage   #4c591c
set $blossom   #f2c438
set $amber     #c29e3b
set $harbor    #4a6d8c
set $sky       #78a4bf
set $iris      #8831c0
set $petal     #a66ec7
set $teal      #256e6e
set $aqua      #548c8a

# No indicator
# target                  title     bg        text      indicator border
client.focused            $sunrise  $base     $text     $petal    $petal
client.focused_inactive   $overlay0 $base     $text     $overlay0 $overlay0
client.unfocused          $overlay0 $base     $text     $overlay0 $overlay0
client.urgent             $solar    $base     $solar    $overlay0 $solar
client.placeholder        $overlay0 $base     $text     $overlay0 $overlay0
client.background         $base

# bar
bar {
    font pango:Iosevka Nerd Font 12
    status_command LANGUAGE=en_US i3blocks
    position top

    colors {
        background         $mantle
        statusline         $text
        focused_statusline $text
        focused_separator  $text

        # target            border    bg        text
        focused_workspace   $mantle   $petal     $mantle
        active_workspace    $mantle   $surface2 $text
        inactive_workspace  $mantle   $mantle   $text
        urgent_workspace    $mantle   $solar    $mantle
    }
}
