[mgr]
linemode = "size"

[preview]
max_width = 1000
max_height = 800

[opener]
drawio = [
    { run = 'drawio "$@"', orgphan = true, desc = "Drawio Desktop" },
]
system_open = [
    { run = 'xdg-open "$@"', orphan = true, desc = "System Open" }
]

[open]
pretend_rules = [
    { url = "*.drawio", use = "drawio" },
    # { url = "*", use = "system_open" }
]
