[common]
# Root directory for your digital assets
working_directory = /home/Allen/Music/Rips

# TLMC-inspired template without the elusive [event] field
# This ensures a clean path that you can easily append to manually
#
# Example: [森羅万象]/2023-11-12 [SBCD-0024] 森羅万象 東方BEST ALBUM 『エモ』/(01) [あやぽんず＊，あよ] カリスマ煉獄天神.flac
track_template = [%%A]/%%y-%%m-%%d [%%c] %%l/(%%n) [%%a] %%t


[drive:ASUS%20%20%20%20%3ASDRW-08D3S-U%20%20%20%20%3AF511]
vendor = ASUS
model = SDRW-08D3S-U
release = F511
read_offset = 6

